### PR TITLE
Update HighchartOption.php

### PR DESCRIPTION
**Pull request by rolandsusans**
fallback for servers that does not have iconv  function enabled

### CODE REVIEW

**Comment by ghunti** [comment]
Thanks

**Comment by rolandsusans** [comment]
Nice. It will be totally cool if you also could make minor release, like v3.0.2 for Composer :+1:

**Comment by ghunti** [comment]
Hehe. Currently I'm away from my PC. Do you know if its possible to create tags here on GitHub?
Cheers

**Comment by rolandsusans** [comment]
Yup, it should be as easy as : 
1. https://github.com/ghunti/HighchartsPHP/releases
2. create new release/tag
Thanks ! :)

**Comment by ghunti** [comment]
Hehe. Nice. Learned onde more thing today. Thanks

**Pull request merged**
