### PR TITLE
PHP 8.1 compatability

### PR DESCRIPTION
**Pull request by Gugiman**
Add return types to Classes that implement ArrayAccess.

Therefore increase the required php version to 7.

Thanks for your work :)

### CODE REVIEW

**Comment by danijelk** [comment]
@ghunti Hi, any chance this will ever be merged?

**Comment by ghunti** [comment]
Hi.
Thanks for the PR. Can you please explain why those changes are needed?

**Comment by ghunti** [comment]
I understand the patch now. The tests are breaking though, can you take a look at them please?

**Comment by ghunti** [comment]
The problem seems to be related with php7. This Patch only seems to work with PHP 8.1 (like the title says), but the bump on PHP version required by composer is only 7, so that confused me.
I will come back to this in the coming days.

**Comment by ghunti** [comment]
Ok, I think it's all set now.
Created a last version (v3.0.4) that supports PHP until 8.0 and the new version (v4.0.0) supports >= PHP 8.0

**Pull request merged**
